volumes:
  dropbox-home:

services:
  dropbox:
    image: ghcr.io/g3nsvrv/dropbox-container:latest
    container_name: ${HOSTNAME}
    hostname: ${HOSTNAME}
    environment:
      - USERACCOUNT=${USERACCOUNT}
      - GROUPACCOUNT=${GROUPACCOUNT}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - dropbox-home:/home/${USERACCOUNT}
    restart: unless-stopped